### PR TITLE
Windows native compilation, minor fixes

### PR DESCRIPTION
**Pull request by Crococode**
I compiled Yaafe on a Windows system using CMake and MinGW. I fixed some minor runtime and compilation issues along the way and documented everything in a tutorial:
https://crococode.wordpress.com/2015/04/01/compiling-yaafe-on-windows-using-cmake-and-mingw/

### CODE REVIEW

**Comment by thomasfillon** [comment]
@Crococode : Sorry for not answering you much sooner and thank you very much for this PR.

If you don't mind could you please submit this pull request against the _dev_ branch ?
I have no idea why the Travis-CI check fails as the error does not seems to be related to your PR.

**Comment by thomasfillon** [comment]
In fact the comment above may explain the Travis-CI failure. 
@Crococode If you agree, could you please fix it and it should then be ok to merge this PR into the master branch. Thank you

**Comment by Crococode** [comment]
Yeah, thank you for the input! Great!

**Comment by thomasfillon** [comment]
That was fast ! 
Thank you very much !

**Pull request merged**
