### PR TITLE
feat: add Python 3 support and get ready for conda-forge

### LINKED ISSUE #41: Getting rid of git submodules to ease migration to conda-forge
I am currently trying to prepare a `conda-forge` release of Yaafe.

`conda-forge` recommends to link to a source archive instead of Github repository.
One way of doing it is to directly link to Yaafe releases in `meta.yaml` file:

```yaml
source:
  fn: yaafe-0.70-rc1.tar.gz
  url: https://github.com/Yaafe/Yaafe/archive/0.70-rc1.tar.gz
```

Unfortunately, this `tar.gz` file does not contain the code of `externals` git submodules `eigen` and `fmemopen`. 

Is there a (legal? technical?) reason not to directly copy `eigen` and `fmemopen` source code in `externals` directory? This would make the `conda-forge` migration seamless...

### PR DESCRIPTION
**Pull request by hbredin**
This pull request starts from @louisabraham and @AbdealiJK work.
+ fixes #41 in order to get ready for a later `conda-forge` automated build
+ fixes py3 str/bytes bug (see commit 5353880313067923da60a38efb12b2c46746b35b)

### CODE REVIEW

**Comment by mckelvin** [comment]
I think it's better to add `fmemopen` as a `git subtree`.

**Comment by hbredin** [comment]
OK. But, then we need to find a way to solve #41? Any idea?

**Comment by hbredin** [comment]
#44 that is also relevant.

**Comment by thomasfillon** [comment]
Hi all !

Great work ! Thank you very much.

I'm actually abroad for some workshop so I don't have the time yet to look at everything.

**Comment by thomasfillon** [comment]
@mckelvin I'm not sure to fully understand the way `git subtree` works. If we use `git subtree` to handle `fmemopen`  how does it get reflected in the Github repository ?

As far as I understand  `git subtree` is just a way to deal with external module on our own local repository and not on Github ? Am I right ? If so, 2258b47 would be enough from the Github repository point of view, isn't it ?

**Comment by thomasfillon** [comment]
It seems OK for me to merge this pull request.
Many thanks to every contributors and reviewers of the different commits include in this PR ! You all did a great job !

#44 should be on the way to get solved now. 

I'm still open to discuss about `git subtree` and to correct 2258b47 if needed.

**Comment by mckelvin** [comment]
> As far as I understand git subtree is just a way to deal with external module on our own local repository and not on Github ? Am I right ? If so, 2258b47 would be enough from the Github repository point of view, isn't it ?

@thomasfillon `git subtree` will include external module both in local repository and on GitHub (after you push to GitHub), just like what 2258b47 do. But not like 2258b47 , git subtree will include the history of the external module and make it clear to upgrade. Since the `fmemopen` is quite stable (last commit is in 3 years ago) now, I think it's OK to copy the source code directly.

**Comment by thomasfillon** [comment]
OK thanks @mckelvin . To get a better understanding, let's say that I use git subtree and push to github. I understand that from my local machine I git subtree will include the git history of the external module.
Let's say now that you pull from github. Would you get the subtree information and the git history ? As far as I understand you do not. Am I wrong ?

**Comment by mckelvin** [comment]
@thomasfillon

No, I'll get the subtree information and the git history. https://github.com/mckelvin/python-ta-lib/tree/build-from-source/vendor/ta-lib is an example where `vendor/ta-lib` is a subtree, added using `git subtree add --prefix vendor/ta-lib https://github.com/TA-Lib/ta-lib.git v0.4.0 --squash (https://github.com/TA-Lib/ta-lib/releases/tag/v0.4.0)`.

When you clone that branch locally (`git clone -b build-from-source https://github.com/mckelvin/python-ta-lib`), you'll have `vendor/ta-lib` already. If you check git log, you'll find that there's only one commit about vendor/ta-lib, that's because I have applied the `--squash` parameter.

**Comment by hbredin** [comment]
As long as Github release archives contain the `fmemopen` source code, I personally have no preference between using `git subtree` or copying the (now stable) source code directly.

**Comment by thomasfillon** [comment]
OK many thanks @mckelvin for your answer. I now have a much better understanding.
I would let the code in this state for now but will consider switching to git subtree latter.

**Pull request merged**
