### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by louisabraham**
Hi, I started from the version #21 by @AbdealiJK, made some minor changes for pathes, and added a cast to make the extensions work.

The command yaafe works with all the features I tested with both python 2 and 3 installations.

The interface should work since I think it is used by the command. I'll test the block per block extraction next week.

### CODE REVIEW

**Comment by thomasfillon** [comment]
Hi !

Thank you very much for your contribution ! this is really great !!!

I will try to find some time next week for reviewing this pull request 
@hbredin : Are you available to help reviewing Python 3 support in Yaafe ?

**Comment by louisabraham** [comment]
Thank you, but @AbdealiJK deserves all the credit.

**Comment by thomasfillon** [comment]
Yes of course ! :+1:

**Comment by hbredin** [comment]
Sorry @thomasfillon, I was out of office for the past few days... 

The first thing I see missing is an update to the `conda.recipe` directory.
It is still unclear to me how to build a Python 3 `conda` package from the repository...

**Comment by louisabraham** [comment]
@hbredin you have a point, I use macOS so I did not consider conda. I have no idea of how to make a conda recipe.
For the moment, this PR is compatible with both python versions, so there may be a way to adapt the same recipe for conda with Python 3.

**Comment by hbredin** [comment]
@louisabraham  `conda` is very useful in `macOS` too :-) I use it all the time!

I just tried this (in macOS):  

```bash
$ conda build --py 3.6 conda.recipe
BUILD START: yaafe-0.70-py36_0
updating index in: /Users/bredin/anaconda2/conda-bld/osx-64
updating index in: /Users/bredin/anaconda2/conda-bld/noarch
Can't build /Users/bredin/Development/Yaafe/conda.recipe due to unsatisfiable dependencies:
Packages missing in current osx-64 channels:
  - libsndfile
  - libmpg123
```

@thomasfillon any idea how `libsndfile` and `libmpg123` conda packages were built? They are the only one missing for `osx-64`.

**Comment by thomasfillon** [comment]
Hi all !

_libsndfile_ and _libmpg123_ conda packages are available through Yaafe conda channel https://anaconda.org/yaafe/repo?type=conda&label=main
They were copied from other anaconda channels. I wil try to find equivalent packages with osx-64 built.

**Comment by thomasfillon** [comment]
I found an osx-64 built for libsndfile. 

Regarding libmpg123, I did the build. Could you please look at the recipe in https://anaconda.org/Yaafe/libmpg123/1.23.1/download/linux-64/libmpg123-1.23.1-0.tar.bz2 and tell me if you could build it for osx-64.
I could then add you as a collaborator in Yaafe anaconda channel to upload the corresponding build.

**Comment by thomasfillon** [comment]
@hbredin The conda recipe for Yaafe includes some tests (see https://github.com/Yaafe/Yaafe/blob/master/conda.recipe/meta.yaml) to check the yaafe binary and python module after the build is successful..

**Comment by hbredin** [comment]
I was able to build `libmpg123`.
However, there is still a problem with `libsndfile`. Trying to build Yaafe, I now get:

```
$ conda build --py 3.6 conda.recipe
BUILD START: yaafe-0.70-py36_0
updating index in: /Users/bredin/anaconda2/conda-bld/osx-64
updating index in: /Users/bredin/anaconda2/conda-bld/noarch
Can't build /Users/bredin/Development/Yaafe/conda.recipe due to unsatisfiable dependencies:
Dependency missing in current osx-64 channels:
  - libsndfile -> libflac
```

**Comment by thomasfillon** [comment]
Ok I see that libflac, libogg and libvorbis miss osx-64 builds. I try to find alternative build right now.

**Comment by thomasfillon** [comment]
Conda forge got them all !

**Comment by thomasfillon** [comment]
@hbredin I hope it should be fine now. All required packages have been copied from conda-forge channel.

**Comment by hbredin** [comment]
Is there a way to update Yaafe's conda.recipe to automatically link to `conda-forge` packages (other than adding `conda-forge` channel with `conda config --add channels conda-forge`)?

This would limit the number of packages you need to maintain in the Yaafe channel...

**Comment by hbredin** [comment]
@louisabraham the build was successful but test failed:

```
===== testing package: yaafe-0.70-py36_0 =====
import: u'yaafelib'
===== yaafe-0.70-py36_0 OK =====
+ /bin/bash -x -e /Users/bredin/anaconda2/conda-bld/conda.recipe_1487687567620/test_tmp/run_test.sh
+ yaafe -h
Usage: yaafe [options]

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -v, --verbose         display more output
  -l, --list            list all available features and output formats
  -d DESCRIBE, --describe=DESCRIBE
                        describe a feature or an output format
  -f FEATUREDEFINITION, --feature=FEATUREDEFINITION
                        feature to extract
  -c CONFIGFILE, --config-file=CONFIGFILE
                        feature extraction plan
  -r SAMPLE_RATE, --rate=SAMPLE_RATE
                        working samplerate in Hz.
  --resample            Resample input signal to the analysis sample rate
  -n, --normalize       normalize input signal by removing mean and scale
                        maximum absolute value to 0.98 (or other value given
                        with --normalize-max)
  --normalize-max=NORMALIZE_MAX
                        Normalize input signal so that maximum absolute value
                        reached given value (see -n, --normalize)
  -i INPUT_LIST, --input=INPUT_LIST
                        text file, each line is an audio file to process
  -b OUT_DIR, --base-dir=OUT_DIR
                        output directory base
  -o FORMAT, --output-format=FORMAT
                        Features output format: csv|h5
  -p key=value, --output-params=key=value
                        add an output format parameter (can be used multiple
                        times, use -l options to list output formats and
                        parameters)
  --dump-dataflow=FILE  output dataflow plan (suitable for process with yaafe-
                        engine)
  --dump-graph=FILE     output dataflow in dot format (suitable for display
                        with graphviz
  -s BUFFER_SIZE, --data-block-size=BUFFER_SIZE
                        Prefered size for data blocks.
  --show=SHOWFEATURES   Show all features in a H5 file
+ yaafe -l
Traceback (most recent call last):
  File "/Users/bredin/anaconda2/conda-bld/conda.recipe_1487687567620/_t_env/bin/yaafe", line 224, in <module>
    main()
  File "/Users/bredin/anaconda2/conda-bld/conda.recipe_1487687567620/_t_env/bin/yaafe", line 156, in main
    listFeatures()
  File "/Users/bredin/anaconda2/conda-bld/conda.recipe_1487687567620/_t_env/bin/yaafe", line 63, in listFeatures
    list_features.extend([' - '+f for f in yaafe.getOutputFormatList()])
  File "/Users/bredin/anaconda2/conda-bld/conda.recipe_1487687567620/_t_env/bin/yaafe", line 63, in <listcomp>
    list_features.extend([' - '+f for f in yaafe.getOutputFormatList()])
TypeError: must be str, not bytes
TESTS FAILED: yaafe-0.70-py36_0
```

**Comment by thomasfillon** [comment]
I need to fully understand how conda-forge works before doing so but I'm thinking about moving Yaafe conda package to conda-forge. As far as I understand it is recommended. 
What do you think of that ?

**Comment by hbredin** [comment]
I think that's the way to go, yes!

**Comment by louisabraham** [comment]
@hbredin sorry, I missed this since I don't use this option. I'll test it and correct it before the weekend.
But you must know it's rather painful to make Python 2 and 3 compatible code, maybe there should be 2 separate folders for the two versions (normally it should be OK, but there are always problems with strings and bytes).

**Comment by tracek** [comment]
Thanks @louisabraham for the effort. "Tested" (just run my scripts in Python 3.5 and verified the result) your changes on my end and so far works smoothly. 

One suggestion: your installation instructions should point to CMAKE_INSTALL_PREFIX rather than default system directory.

**Comment by hbredin** [comment]
@thomasfillon, any news about conda-forge support?

**Comment by hbredin** [comment]
@thomasfillon FYI I am currently working on making Yaafe dependencies available on `conda-forge`:

See https://github.com/conda-forge/staged-recipes/pull/2685

**Pull request merged**
